// Auto-generated from TechSavvy_Merchant_Outreach_Checklist.xlsx – DO NOT EDIT
export const OUTREACH_SEED: { name: string; address: string; category: string; type: string; phone: string; rating: number | null }[] = [
  { name: "Zippy's McCully", address: "1725 S King St, Honolulu, HI", category: "RESTAURANTS & FOOD", type: "Restaurant", phone: "(808) 973-0877", rating: 4.1 },
  { name: "Chong Qing Cuisine", address: "1738 S King St #101, Honolulu, HI", category: "RESTAURANTS & FOOD", type: "Restaurant", phone: "(808) 741-2297", rating: 4.7 },
  { name: "Gyotaku Japanese Restaurant", address: "1824 S King St, Honolulu, HI", category: "RESTAURANTS & FOOD", type: "Restaurant", phone: "(808) 949-4584", rating: 4.4 },
  { name: "Mr Ojisan Neo Bar & Sushi", address: "1785 S King St, Honolulu, HI", category: "RESTAURANTS & FOOD", type: "Restaurant", phone: "(808) 735-4455", rating: 4.6 },
  { name: "Hana Market", address: "930 McCully St, Honolulu, HI", category: "RESTAURANTS & FOOD", type: "Restaurant/Grocery", phone: "(808) 591-1184", rating: 5 },
  { name: "Moobongri Soup & Yakiniku", address: "930 McCully St, Honolulu, HI", category: "RESTAURANTS & FOOD", type: "Restaurant", phone: "(808) 200-5687", rating: 4.6 },
  { name: "Choi's Family Restaurant", address: "930 McCully St, Honolulu, HI", category: "RESTAURANTS & FOOD", type: "Restaurant", phone: "(808) 591-1184", rating: 4.3 },
  { name: "FUJIYAMA TEXAS", address: "2065 S King St, Honolulu, HI", category: "RESTAURANTS & FOOD", type: "Restaurant", phone: "(808) 955-0738", rating: 4.6 },
  { name: "Chiang Mai Thai Cuisine", address: "2239 S King St, Honolulu, HI", category: "RESTAURANTS & FOOD", type: "Restaurant", phone: "(808) 941-1151", rating: 4.4 },
  { name: "Thai Issan Cuisine II", address: "2334 S King St, Honolulu, HI", category: "RESTAURANTS & FOOD", type: "Restaurant", phone: "(808) 944-8060", rating: 4.5 },
  { name: "Fresh Bites Hawaii", address: "2334 S King St, Honolulu, HI", category: "RESTAURANTS & FOOD", type: "Restaurant", phone: "(808) 200-1139", rating: 4.7 },
  { name: "Minatoku Kitchen", address: "2471 S King St, Honolulu, HI", category: "RESTAURANTS & FOOD", type: "Restaurant", phone: "(808) 312-8633", rating: 4.5 },
  { name: "hana no sato", address: "2671 S King St, Honolulu, HI", category: "RESTAURANTS & FOOD", type: "Restaurant", phone: "(808) 949-2679", rating: 4.5 },
  { name: "LaCiccia Honolulu", address: "2700 S King St, Honolulu, HI", category: "RESTAURANTS & FOOD", type: "Restaurant", phone: "(808) 773-8688", rating: 4.3 },
  { name: "Kahai Street Kitchen", address: "946 Coolidge St, Honolulu, HI", category: "RESTAURANTS & FOOD", type: "Restaurant", phone: "(808) 845-0320", rating: 4.6 },
  { name: "Oh My Grill", address: "1960 Kapiolani Blvd #102, Honolulu, HI", category: "RESTAURANTS & FOOD", type: "Restaurant", phone: "(808) 664-2121", rating: 4 },
  { name: "Cucina Moon", address: "1960 Kapiolani Blvd #211, Honolulu, HI", category: "RESTAURANTS & FOOD", type: "Restaurant", phone: "(808) 200-5933", rating: 4.3 },
  { name: "Fig & Ginger Honolulu", address: "1960 Kapiolani Blvd #103, Honolulu, HI", category: "RESTAURANTS & FOOD", type: "Restaurant", phone: "(808) 501-7249", rating: 4.4 },
  { name: "McCully 11X", address: "1110 McCully St, Honolulu, HI", category: "RESTAURANTS & FOOD", type: "Restaurant", phone: "(808) 840-0496", rating: 4.8 },
  { name: "Honolulu Coffee Company", address: "2643 S King St, Honolulu, HI", category: "COFFEE & CAFE", type: "Coffee Shop", phone: "", rating: 3.9 },
  { name: "Bakery on King (HCC)", address: "2643 S King St, Honolulu, HI", category: "COFFEE & CAFE", type: "Bakery/Cafe", phone: "(808) 202-2562", rating: 3.9 },
  { name: "Coffee or Tea?", address: "1960 Kapiolani Blvd #106, Honolulu, HI", category: "COFFEE & CAFE", type: "Boba/Tea", phone: "(808) 942-4357", rating: 4.2 },
  { name: "Cafe KYRA", address: "801 Kaheka St #A7, Honolulu, HI", category: "COFFEE & CAFE", type: "Cafe", phone: "(808) 941-4512", rating: 4.7 },
  { name: "Honolulu Kitchen Little Corner Cafe", address: "914 Coolidge St, Honolulu, HI", category: "COFFEE & CAFE", type: "Cafe", phone: "(808) 260-1192", rating: 4.9 },
  { name: "Sunny's Local Grind", address: "464 Ena Rd, Honolulu, HI", category: "COFFEE & CAFE", type: "Cafe/Breakfast", phone: "", rating: 4.7 },
  { name: "Shoreline Cafe", address: "2113 Kalakaua Ave #104, Honolulu, HI", category: "COFFEE & CAFE", type: "Coffee Shop", phone: "", rating: 4.8 },
  { name: "Pai Cafe Coffee & Acai Bowls", address: "755 Kapahulu Ave, Honolulu, HI", category: "COFFEE & CAFE", type: "Cafe", phone: "(808) 807-9576", rating: 4.9 },
  { name: "Paniolo Bar & Cafe", address: "1696 Ala Moana Blvd, Honolulu, HI", category: "COFFEE & CAFE", type: "Bar/Cafe", phone: "(808) 949-0061", rating: 4.6 },
  { name: "Times Supermarket - McCully", address: "1772 S King St, Honolulu, HI", category: "GROCERY & SUPERMARKET", type: "Supermarket", phone: "(808) 973-5868", rating: 4.2 },
  { name: "Down to Earth Organic & Natural", address: "2525 S King St, Honolulu, HI", category: "GROCERY & SUPERMARKET", type: "Health Food", phone: "(808) 947-7678", rating: 4.5 },
  { name: "MONO", address: "2013 S King St, Honolulu, HI", category: "RETAIL & SPECIALTY SHOPS", type: "Stationery/Gifts", phone: "(808) 955-1595", rating: 5 },
  { name: "Truest Hawaii", address: "2011 S King St, Honolulu, HI", category: "RETAIL & SPECIALTY SHOPS", type: "Sneaker Boutique", phone: "(808) 946-4202", rating: 4.1 },
  { name: "Consignment Center", address: "1901 S King St, Honolulu, HI", category: "RETAIL & SPECIALTY SHOPS", type: "Furniture/Antiques", phone: "(808) 382-8240", rating: 4.5 },
  { name: "BIKEFACTORY Hawaii", address: "1969 S King St, Honolulu, HI", category: "RETAIL & SPECIALTY SHOPS", type: "Bicycle Store", phone: "(808) 596-8844", rating: 4.6 },
  { name: "McCully Bicycle & Sporting Goods", address: "2124 S King St, Honolulu, HI", category: "RETAIL & SPECIALTY SHOPS", type: "Sporting Goods", phone: "(808) 955-6329", rating: 4.6 },
  { name: "Keiki 2 Keiki", address: "2758 S King St, Honolulu, HI", category: "RETAIL & SPECIALTY SHOPS", type: "Kids Consignment", phone: "(808) 739-5437", rating: 4.4 },
  { name: "Hawaiian Graphics", address: "1923 S Beretania St, Honolulu, HI", category: "RETAIL & SPECIALTY SHOPS", type: "Art Supplies", phone: "(808) 973-7171", rating: 4.6 },
  { name: "mobi", address: "1668 S King St #101, Honolulu, HI", category: "RETAIL & SPECIALTY SHOPS", type: "Cell Phone Store", phone: "(808) 723-2097", rating: 4.7 },
  { name: "One University Stop", address: "2658 S King St, Honolulu, HI", category: "RETAIL & SPECIALTY SHOPS", type: "Convenience Store", phone: "(808) 942-1111", rating: 5 },
  { name: "Longs Drugs (CVS)", address: "2470 S King St, Honolulu, HI", category: "PHARMACY & HEALTH", type: "Pharmacy", phone: "(808) 947-2651", rating: 3.7 },
  { name: "Times McCully Pharmacy", address: "1772 S King St, Honolulu, HI", category: "PHARMACY & HEALTH", type: "Pharmacy", phone: "(808) 973-5851", rating: 4 },
  { name: "McCully Shopping Center", address: "1960 Kapiolani Blvd, Honolulu, HI", category: "SHOPPING CENTERS", type: "Shopping Mall", phone: "(808) 955-7377", rating: 4 },
  { name: "Old Stadium Square", address: "2320 S King St, Honolulu, HI", category: "SHOPPING CENTERS", type: "Shopping Center", phone: "", rating: 3.5 },
  { name: "Puck's Alley", address: "2600 S King St, Honolulu, HI", category: "SHOPPING CENTERS", type: "Shopping Center", phone: "", rating: 4 },
  { name: "McCully Barber Shop", address: "841 McCully St #A, Honolulu, HI", category: "BARBER & SALON", type: "Barber", phone: "(808) 946-6413", rating: 4.6 },
  { name: "Mojo Barbershop", address: "2005 S King St, Honolulu, HI", category: "BARBER & SALON", type: "Barber", phone: "(808) 800-3960", rating: 4.6 },
  { name: "K J's Men's & Women's Hairstyling", address: "2749 S King St, Honolulu, HI", category: "BARBER & SALON", type: "Salon", phone: "(808) 949-0360", rating: 4.5 },
  { name: "Mai's Beauty Salon", address: "2080 S King St, Honolulu, HI", category: "BARBER & SALON", type: "Salon", phone: "(808) 734-0344", rating: 4.8 },
  { name: "N. barber", address: "931 University Ave, Honolulu, HI", category: "BARBER & SALON", type: "Barber", phone: "(808) 382-2899", rating: 5 },
  { name: "Artesian Auto Repair LLC", address: "1012 Artesian St, Honolulu, HI", category: "AUTO REPAIR & SERVICE", type: "Auto Repair", phone: "(808) 947-3011", rating: 4.8 },
  { name: "McCully Union Service", address: "2105 S Beretania St, Honolulu, HI", category: "AUTO REPAIR & SERVICE", type: "Auto Repair/Tires", phone: "(808) 951-4753", rating: 4.8 },
  { name: "Punahou Auto Service", address: "1558 S King St, Honolulu, HI", category: "AUTO REPAIR & SERVICE", type: "Auto Repair", phone: "(808) 941-2411", rating: 4.4 },
  { name: "Tony's Auto Air", address: "1016 Artesian St, Honolulu, HI", category: "AUTO REPAIR & SERVICE", type: "Auto AC Repair", phone: "(808) 955-0866", rating: 4.6 },
  { name: "Masaki's Auto Repair", address: "2211 S Beretania St, Honolulu, HI", category: "AUTO REPAIR & SERVICE", type: "Auto Repair", phone: "(808) 943-1550", rating: 4.3 },
  { name: "Launderland I", address: "2025 S Beretania St #1, Honolulu, HI", category: "LAUNDRY & DRY CLEANING", type: "Laundromat", phone: "(808) 955-7305", rating: 3.6 },
  { name: "Ena Laundry", address: "478 Ena Rd, Honolulu, HI", category: "LAUNDRY & DRY CLEANING", type: "Laundromat", phone: "(808) 942-3451", rating: 4.5 },
  { name: "iDo Laundry", address: "1922 Kalakaua Ave, Honolulu, HI", category: "LAUNDRY & DRY CLEANING", type: "Laundromat", phone: "(808) 926-2573", rating: 3.6 },
  { name: "Sheridan Laundry Center", address: "1334 Young St #105, Honolulu, HI", category: "LAUNDRY & DRY CLEANING", type: "Dry Cleaner", phone: "(808) 597-8035", rating: 4.3 },
  { name: "HNL Dentistry of Moiliili", address: "934 Punahou St, Honolulu, HI", category: "DENTAL & MEDICAL", type: "Dentist", phone: "(808) 949-8341", rating: 5 },
  { name: "McCully-Moiliili Dentist", address: "905 Makahiki Way, Honolulu, HI", category: "DENTAL & MEDICAL", type: "Dentist", phone: "(808) 489-9555", rating: 5 },
  { name: "McCully Dental Center", address: "1953 S Beretania St, Honolulu, HI", category: "DENTAL & MEDICAL", type: "Dentist", phone: "(808) 791-0200", rating: 5 },
  { name: "Waikiki Health Clinic", address: "935 Makahiki Way, Honolulu, HI", category: "DENTAL & MEDICAL", type: "Medical Clinic", phone: "(808) 922-4787", rating: 4.2 },
  { name: "Takiguchi Dental Group", address: "2525 S King St #305, Honolulu, HI", category: "DENTAL & MEDICAL", type: "Dentist", phone: "(808) 949-2378", rating: 5 },
  { name: "Mo'ili'ili Fitness", address: "2463 S King St, Honolulu, HI", category: "FITNESS & YOGA", type: "Gym/CrossFit", phone: "(808) 427-1157", rating: 5 },
  { name: "The Bar Method Honolulu", address: "2758 S King St #206, Honolulu, HI", category: "FITNESS & YOGA", type: "Fitness Studio", phone: "", rating: 4.8 },
  { name: "Egan's Fitness Honolulu", address: "1212 Punahou St, Honolulu, HI", category: "FITNESS & YOGA", type: "Bootcamp", phone: "(808) 271-3779", rating: 4.9 },
  { name: "Power Yoga Hawaii", address: "510 Piikoi St #200, Honolulu, HI", category: "FITNESS & YOGA", type: "Yoga Studio", phone: "(808) 698-6414", rating: 4.6 },
  { name: "Body Balance Hawai'i", address: "1450 Ala Moana Blvd #1235, Honolulu, HI", category: "FITNESS & YOGA", type: "Pilates/Cycling", phone: "(808) 542-9597", rating: 4.9 },
  { name: "CiCi Nails", address: "1960 Kapiolani Blvd, Honolulu, HI", category: "NAIL SALONS & SPA", type: "Nail Salon", phone: "(808) 949-9494", rating: 4.8 },
  { name: "Moonlight Nails & Spa", address: "1440 Kapiolani Blvd #105, Honolulu, HI", category: "NAIL SALONS & SPA", type: "Nail Salon", phone: "(808) 888-0455", rating: 5 },
  { name: "Honolulu Nails", address: "931 University Ave #106, Honolulu, HI", category: "NAIL SALONS & SPA", type: "Nail Salon", phone: "(808) 949-1600", rating: 4.4 },
  { name: "Nail Story", address: "931 University Ave #102, Honolulu, HI", category: "NAIL SALONS & SPA", type: "Nail Salon", phone: "(808) 232-8435", rating: 4.2 },
  { name: "Apple Nails Spa", address: "1665 Makaloa St, Honolulu, HI", category: "NAIL SALONS & SPA", type: "Nail Salon", phone: "(808) 946-2590", rating: 4.9 },
  { name: "Moana Nails", address: "435 Atkinson Dr, Honolulu, HI", category: "NAIL SALONS & SPA", type: "Nail Salon", phone: "(808) 436-2840", rating: 4.9 },
  { name: "Nani Nails Salon", address: "2741 S King St, Honolulu, HI", category: "NAIL SALONS & SPA", type: "Nail Salon", phone: "(808) 947-4116", rating: 4.8 },
  { name: "Lily's Nail Spa & Hair Salon", address: "1442 Kona St, Honolulu, HI", category: "NAIL SALONS & SPA", type: "Nail/Hair Salon", phone: "(808) 942-1668", rating: 4.6 },
  { name: "WEN Massage Spa", address: "1750 Kalakaua Ave #2402, Honolulu, HI", category: "NAIL SALONS & SPA", type: "Massage Spa", phone: "(808) 796-6658", rating: 5 },
  { name: "Rock Star Tattoos & Piercings", address: "847 McCully St #A, Honolulu, HI", category: "TATTOO & PIERCING", type: "Tattoo/Piercing", phone: "(808) 791-7879", rating: 4.9 },
  { name: "Soul Signature Tattoo", address: "1750 Kalakaua Ave 2nd fl, Honolulu, HI", category: "TATTOO & PIERCING", type: "Tattoo", phone: "(808) 369-6652", rating: 5 },
  { name: "Tattoolicious Tattoo Waikiki", address: "1909 Ala Wai Blvd C1, Honolulu, HI", category: "TATTOO & PIERCING", type: "Tattoo", phone: "(808) 949-8287", rating: 4.8 },
  { name: "Sacred Art Tattoo & Coffee Bar", address: "1925 Kalakaua Ave #A, Honolulu, HI", category: "TATTOO & PIERCING", type: "Tattoo/Coffee", phone: "(808) 744-0880", rating: 4.9 },
  { name: "Heart of Town Pet Food", address: "2080 S King St, Honolulu, HI", category: "PET CARE & VET", type: "Pet Store", phone: "(808) 744-2979", rating: 4.6 },
  { name: "King Street Pet Hospital", address: "2016 S King St, Honolulu, HI", category: "PET CARE & VET", type: "Veterinary", phone: "(808) 951-7777", rating: 4.7 },
  { name: "The Pet Clinic", address: "1947 S Beretania St, Honolulu, HI", category: "PET CARE & VET", type: "Veterinary", phone: "(808) 946-5096", rating: 4.8 },
  { name: "Honolulu Dog Spa", address: "2115 Young St, Honolulu, HI", category: "PET CARE & VET", type: "Pet Grooming", phone: "(808) 626-5865", rating: 4.6 },
  { name: "All Dogs Grooming Honolulu", address: "1411 Kalakaua Ave, Honolulu, HI", category: "PET CARE & VET", type: "Pet Grooming", phone: "(808) 799-0988", rating: 4.9 },
  { name: "Dogmama808", address: "1481 S King St #150, Honolulu, HI", category: "PET CARE & VET", type: "Pet Store", phone: "(808) 600-9300", rating: 4.7 },
  { name: "Flowers For A Friend", address: "2739 S King St, Honolulu, HI", category: "FLORIST & LEI", type: "Florist", phone: "(808) 955-4227", rating: 4.7 },
  { name: "Hanapua Flowers", address: "2043 S Beretania St, Honolulu, HI", category: "FLORIST & LEI", type: "Florist", phone: "(808) 892-1711", rating: 4.9 },
  { name: "Paradise Leis", address: "2065 S King St #101, Honolulu, HI", category: "FLORIST & LEI", type: "Lei Shop", phone: "(808) 762-0256", rating: 5 },
  { name: "Pink Clover", address: "2239 S King St, Honolulu, HI", category: "FLORIST & LEI", type: "Florist", phone: "(808) 673-5427", rating: 5 },
  { name: "Flowers' N Fun", address: "1210 Artesian St #102, Honolulu, HI", category: "FLORIST & LEI", type: "Florist", phone: "(808) 941-5874", rating: 5 },
  { name: "Flowers By Jr Lou & T", address: "2652 S King St, Honolulu, HI", category: "FLORIST & LEI", type: "Florist", phone: "", rating: 5 },
  { name: "Summer Burnett - State Farm", address: "1806 S King St #32, Honolulu, HI", category: "INSURANCE", type: "Insurance", phone: "(808) 988-7011", rating: 5 },
  { name: "Hawaiian Life Insurance", address: "1440 Kapiolani Blvd #1525, Honolulu, HI", category: "INSURANCE", type: "Insurance", phone: "(808) 942-6541", rating: 5 },
  { name: "Insurance Agency Hawaii LLC", address: "1314 S King St #962, Honolulu, HI", category: "INSURANCE", type: "Insurance", phone: "(808) 524-6626", rating: 3.3 },
  { name: "SR Drivers Insurance Solutions", address: "1019 University Ave, Honolulu, HI", category: "INSURANCE", type: "Insurance", phone: "(808) 374-9111", rating: 5 },
  { name: "Brown & Brown Insurance", address: "1585 Kapiolani Blvd #1215, Honolulu, HI", category: "INSURANCE", type: "Insurance", phone: "(808) 540-3333", rating: null },
  { name: "At Home Hawaii Real Estate", address: "1750 Kalakaua Ave #2108, Honolulu, HI", category: "REAL ESTATE", type: "Real Estate", phone: "(808) 954-6435", rating: 4.6 },
  { name: "TY Realty Inc", address: "1750 Kalakaua Ave #209, Honolulu, HI", category: "REAL ESTATE", type: "Real Estate", phone: "(808) 941-6675", rating: 4.7 },
  { name: "NAI CBI Hawaii", address: "1712 S King St #201, Honolulu, HI", category: "REAL ESTATE", type: "Real Estate", phone: "(808) 942-7100", rating: 4.1 },
  { name: "Sakuma Realty Inc", address: "1773 S King St, Honolulu, HI", category: "REAL ESTATE", type: "Real Estate", phone: "(808) 943-2725", rating: 2.4 },
  { name: "Keller Williams Honolulu", address: "1347 Kapiolani Blvd #300, Honolulu, HI", category: "REAL ESTATE", type: "Real Estate", phone: "(808) 596-2888", rating: 4.5 },
  { name: "Honolulu Federal Credit Union", address: "2305 S Beretania St, Honolulu, HI", category: "FINANCIAL / CREDIT UNION", type: "Credit Union", phone: "(808) 777-5646", rating: 4.4 },
  { name: "UH Federal Credit Union", address: "2019 S King St, Honolulu, HI", category: "FINANCIAL / CREDIT UNION", type: "Credit Union", phone: "(808) 983-5500", rating: 4.4 },
  { name: "Aloha Credit Card Processing", address: "425 Ena Rd, Honolulu, HI", category: "FINANCIAL / CREDIT UNION", type: "Payment Processing", phone: "(808) 551-7342", rating: 4 },
  { name: "Honolulu Time Co.", address: "1311 Kapiolani Blvd #101, Honolulu, HI", category: "JEWELRY & WATCH", type: "Watch Store", phone: "(808) 591-2611", rating: 4.1 },
  { name: "Solitaire Jewelers", address: "1750 Kalakaua Ave #105, Honolulu, HI", category: "JEWELRY & WATCH", type: "Jewelry", phone: "(808) 955-3333", rating: 4.8 },
  { name: "Waikiki Gold and Silver", address: "1421 Kalakaua Ave, Honolulu, HI", category: "JEWELRY & WATCH", type: "Jewelry/Pawn", phone: "(808) 861-4653", rating: 4.7 },
  { name: "Robert Palma Designs", address: "1750 Kalakaua Ave #3702, Honolulu, HI", category: "JEWELRY & WATCH", type: "Custom Jewelry", phone: "(808) 946-4332", rating: 5 },
  { name: "Bags End Gold And Pawn", address: "1676 Kalakaua Ave, Honolulu, HI", category: "JEWELRY & WATCH", type: "Pawn Shop", phone: "(808) 949-5115", rating: 3.9 },
  { name: "The Watch Repair Shop", address: "2092 Kuhio Ave, Honolulu, HI", category: "JEWELRY & WATCH", type: "Watch Repair", phone: "(808) 382-9871", rating: 4.9 },
  { name: "Ala Moana Pawn Shop", address: "550 Piikoi St, Honolulu, HI", category: "JEWELRY & WATCH", type: "Pawn Shop", phone: "(808) 596-7787", rating: 4.7 },
  { name: "Gourmet Liquors", address: "2437 S King St, Honolulu, HI", category: "LIQUOR STORE", type: "Liquor Store", phone: "", rating: 3.9 },
  { name: "Bev Mart", address: "2441 Date St, Honolulu, HI", category: "LIQUOR STORE", type: "Liquor Store", phone: "(808) 949-9000", rating: 4.3 },
  { name: "777 Liquors Grocery & Gift", address: "931 University Ave #107, Honolulu, HI", category: "LIQUOR STORE", type: "Liquor Store", phone: "(808) 946-5779", rating: 4.3 },
  { name: "FedEx Office Print & Ship", address: "1500 Kapiolani Blvd, Honolulu, HI", category: "PRINT / SHIP / OFFICE", type: "Print/Ship", phone: "(808) 944-8500", rating: 2.9 },
  { name: "The UPS Store (Makaloa)", address: "1670 Makaloa St, Honolulu, HI", category: "PRINT / SHIP / OFFICE", type: "Print/Ship", phone: "(808) 943-0877", rating: 2.5 },
  { name: "Copy Hut", address: "2503 S King St, Honolulu, HI", category: "PRINT / SHIP / OFFICE", type: "Print Shop", phone: "(808) 941-5252", rating: 5 },
  { name: "Excel Learning Center", address: "1914 S King St #203, Honolulu, HI", category: "TUTORING & EDUCATION", type: "Tutoring", phone: "(808) 955-9388", rating: 5 },
  { name: "Quick Stars Tutoring", address: "1806 S King St #35, Honolulu, HI", category: "TUTORING & EDUCATION", type: "Tutoring", phone: "(808) 375-5244", rating: 5 },
  { name: "Solomon Learning Center", address: "1311 Kapiolani Blvd #605, Honolulu, HI", category: "TUTORING & EDUCATION", type: "Tutoring", phone: "(808) 727-9203", rating: 4.9 },
  { name: "Dr. Takahashi Juku", address: "2304 S King St #201, Honolulu, HI", category: "TUTORING & EDUCATION", type: "Tutoring", phone: "(808) 949-3366", rating: 3.4 },
  { name: "Kumon - Moiliili", address: "1212 University Ave, Honolulu, HI", category: "TUTORING & EDUCATION", type: "Tutoring", phone: "(808) 492-8179", rating: null },
  { name: "Chinese Herbs & Acupuncture", address: "1911 S King St #A, Honolulu, HI", category: "CHIROPRACTIC / ACUPUNCTURE / WELLNESS", type: "Acupuncture", phone: "(808) 947-7103", rating: 4.7 },
  { name: "Ohana Healing Center", address: "1481 S King St #321, Honolulu, HI", category: "CHIROPRACTIC / ACUPUNCTURE / WELLNESS", type: "Wellness", phone: "(808) 944-0088", rating: 5 },
  { name: "Honolulu Chiropractic Pain Relief", address: "1314 S King St #1655, Honolulu, HI", category: "CHIROPRACTIC / ACUPUNCTURE / WELLNESS", type: "Chiropractor", phone: "(808) 924-7246", rating: 4.9 },
  { name: "TRIO Health Chiro & Shockwave", address: "1314 S King St #1264, Honolulu, HI", category: "CHIROPRACTIC / ACUPUNCTURE / WELLNESS", type: "Chiropractor", phone: "(808) 465-4700", rating: 4.9 },
  { name: "Taira Chiropractic", address: "2525 S King St #304, Honolulu, HI", category: "CHIROPRACTIC / ACUPUNCTURE / WELLNESS", type: "Chiropractor", phone: "(808) 948-8722", rating: 4.5 },
  { name: "Acupuncture & Wellness Center", address: "1150 S King St #302, Honolulu, HI", category: "CHIROPRACTIC / ACUPUNCTURE / WELLNESS", type: "Acupuncture", phone: "(808) 319-7791", rating: 5 },
  { name: "The Pain Relief Center", address: "750 Kapahulu Ave #D, Honolulu, HI", category: "CHIROPRACTIC / ACUPUNCTURE / WELLNESS", type: "Massage/Bodywork", phone: "(808) 386-6763", rating: 4.9 },
  { name: "Vape Kings LLC", address: "943 Hauoli St, Honolulu, HI", category: "SMOKE SHOP / VAPE / TOBACCO", type: "Vape Shop", phone: "(808) 892-3547", rating: 4.8 },
  { name: "Hawaii Cheapest Vape Shop - University", address: "931 University Ave #104, Honolulu, HI", category: "SMOKE SHOP / VAPE / TOBACCO", type: "Vape Shop", phone: "(808) 376-8226", rating: 4.2 },
  { name: "SMOKE BREAK VAPE TOBACCO", address: "1438 Kona St A, Honolulu, HI", category: "SMOKE SHOP / VAPE / TOBACCO", type: "Smoke Shop", phone: "(808) 751-7967", rating: 5 },
  { name: "Pipeline Smokeshop", address: "1019 University Ave #208, Honolulu, HI", category: "SMOKE SHOP / VAPE / TOBACCO", type: "Smoke Shop", phone: "(808) 942-4700", rating: 4.8 },
  { name: "Hawaii's Cheapest Vape - Makaloa", address: "1538 Makaloa St, Honolulu, HI", category: "SMOKE SHOP / VAPE / TOBACCO", type: "Vape Shop", phone: "(808) 517-4413", rating: 4.5 },
  { name: "Vape Hawaii", address: "1665 Kalakaua Ave #103, Honolulu, HI", category: "SMOKE SHOP / VAPE / TOBACCO", type: "Vape Shop", phone: "(808) 941-6157", rating: 4.4 },
  { name: "Choke Smoke and Vape Planet", address: "2671-C S King St, Honolulu, HI", category: "SMOKE SHOP / VAPE / TOBACCO", type: "Smoke Shop", phone: "(808) 944-4200", rating: 4.6 },
  { name: "Tobaccos of Hawaii", address: "2043 S Beretania St #B, Honolulu, HI", category: "SMOKE SHOP / VAPE / TOBACCO", type: "Tobacco/Cigar", phone: "(808) 942-7855", rating: 4.7 },
  { name: "Vape X", address: "826 Kaheka St #102, Honolulu, HI", category: "SMOKE SHOP / VAPE / TOBACCO", type: "Vape Shop", phone: "(808) 207-9628", rating: 4.9 },
  { name: "Hawaii Kratom THC & Hookah", address: "931 University Ave, Honolulu, HI", category: "SMOKE SHOP / VAPE / TOBACCO", type: "Smoke Shop", phone: "(808) 376-8231", rating: 4.4 },
  { name: "808 Eye Care", address: "1820 Algaroba St #200, Honolulu, HI", category: "OPTOMETRIST / EYE CARE", type: "Optometrist", phone: "(808) 949-9999", rating: 4.9 },
  { name: "Eye Care Associates of Hawaii", address: "1441 Kapiolani Blvd #1520, Honolulu, HI", category: "OPTOMETRIST / EYE CARE", type: "Optometrist", phone: "(808) 973-2015", rating: 4.9 },
  { name: "Dream Vision Eye Care", address: "1221 Kapiolani Blvd #120, Honolulu, HI", category: "OPTOMETRIST / EYE CARE", type: "Optometrist", phone: "(808) 596-4445", rating: 4.8 },
  { name: "Lins Eye Care LLC", address: "700 Keeaumoku St, Honolulu, HI", category: "OPTOMETRIST / EYE CARE", type: "Optometrist", phone: "(808) 949-3937", rating: 5 },
  { name: "KM Eye Care", address: "1401 S Beretania St #570, Honolulu, HI", category: "OPTOMETRIST / EYE CARE", type: "Optometrist", phone: "(808) 735-7633", rating: 4.8 },
  { name: "Dr. Trinh Pham & Associates", address: "1450 Ala Moana Blvd #3053, Honolulu, HI", category: "OPTOMETRIST / EYE CARE", type: "Optometrist", phone: "(808) 945-3539", rating: 4.9 },
  { name: "LensCrafters Ala Moana", address: "1450 Ala Moana Blvd #3053, Honolulu, HI", category: "OPTOMETRIST / EYE CARE", type: "Eyewear", phone: "(808) 947-3805", rating: 4.9 },
  { name: "Hawaii Vision Associates", address: "750 Keeaumoku St, Honolulu, HI", category: "OPTOMETRIST / EYE CARE", type: "Optometrist", phone: "(808) 945-3937", rating: 4.2 },
  { name: "NUI MONO", address: "2745 S King St, Honolulu, HI", category: "CLOTHING BOUTIQUE", type: "Clothing", phone: "(808) 946-7407", rating: 5 },
  { name: "Manuhealii Inc", address: "930 Punahou St, Honolulu, HI", category: "CLOTHING BOUTIQUE", type: "Hawaiian Clothing", phone: "(808) 942-9868", rating: 4.5 },
  { name: "Posh Hawaii Women's Boutique", address: "1311 Kapiolani Blvd #414, Honolulu, HI", category: "CLOTHING BOUTIQUE", type: "Boutique", phone: "(808) 205-1949", rating: 4.5 },
  { name: "Mahina Clothing", address: "226 Lewers St, Honolulu, HI", category: "CLOTHING BOUTIQUE", type: "Boutique", phone: "(808) 924-5500", rating: 4.5 },
  { name: "Pitacus Chop Art", address: "2535 S King St, Honolulu, HI", category: "CLOTHING BOUTIQUE", type: "Boutique", phone: "", rating: 4.2 },
  { name: "La Beau Boutique", address: "1331 Makaloa St #M-1, Honolulu, HI", category: "CLOTHING BOUTIQUE", type: "Boutique", phone: "(808) 942-7651", rating: 4.1 },
  { name: "Ten Tomorrow", address: "1114 11th Ave, Honolulu, HI", category: "CLOTHING BOUTIQUE", type: "Boutique", phone: "(808) 591-6219", rating: 4.9 },
  { name: "Sachi's Sweets", address: "2080 S King St, Honolulu, HI", category: "BAKERY / DESSERT / DONUT", type: "Bakery", phone: "", rating: 4.9 },
  { name: "Leonard's Bakery", address: "933 Kapahulu Ave, Honolulu, HI", category: "BAKERY / DESSERT / DONUT", type: "Bakery", phone: "(808) 737-5591", rating: 4.6 },
  { name: "kulu kulu", address: "438 Hobron Ln #102, Honolulu, HI", category: "BAKERY / DESSERT / DONUT", type: "Bakery", phone: "(808) 931-0506", rating: 4.7 },
  { name: "Tous les Jours", address: "711 Keeaumoku St, Honolulu, HI", category: "BAKERY / DESSERT / DONUT", type: "Bakery", phone: "(808) 762-9797", rating: 3.5 },
  { name: "Liliha Bakery Ala Moana", address: "1450 Ala Moana Blvd #1300, Honolulu, HI", category: "BAKERY / DESSERT / DONUT", type: "Bakery/Restaurant", phone: "(808) 944-4088", rating: 4.3 },
  { name: "Holey Grail Donuts", address: "1001 Queen St #101, Honolulu, HI", category: "BAKERY / DESSERT / DONUT", type: "Donut Shop", phone: "(808) 482-0311", rating: 4.5 },
  { name: "Little Vessels Donut Co.", address: "3458 Waialae Ave, Honolulu, HI", category: "BAKERY / DESSERT / DONUT", type: "Donut Shop", phone: "(646) 470-4882", rating: 4.8 },
  { name: "Chocolate And Vanilla Bakery", address: "1115 12th Ave, Honolulu, HI", category: "BAKERY / DESSERT / DONUT", type: "Bakery", phone: "(808) 737-2462", rating: 4.6 },
  { name: "76 (Beretania)", address: "1406 S Beretania St, Honolulu, HI", category: "GAS STATION / CAR WASH", type: "Gas Station/Car Wash", phone: "(808) 942-7676", rating: 3.5 },
  { name: "76 (Young St)", address: "1542 Young St, Honolulu, HI", category: "GAS STATION / CAR WASH", type: "Gas Station", phone: "(808) 946-3382", rating: 4 },
  { name: "76 (King St McCully)", address: "2105 S King St, Honolulu, HI", category: "GAS STATION / CAR WASH", type: "Gas Station", phone: "", rating: 4 },
  { name: "76 (University)", address: "2646 S King St, Honolulu, HI", category: "GAS STATION / CAR WASH", type: "Gas Station", phone: "", rating: 3.8 },
  { name: "Shell (McCully)", address: "1115 McCully St, Honolulu, HI", category: "GAS STATION / CAR WASH", type: "Gas Station", phone: "(808) 949-0667", rating: 3.7 },
  { name: "Hele", address: "1549 S King St, Honolulu, HI", category: "GAS STATION / CAR WASH", type: "Gas Station", phone: "(808) 973-1269", rating: 4.1 },
  { name: "Yajima Service Station", address: "1375 S King St, Honolulu, HI", category: "GAS STATION / CAR WASH", type: "Car Wash/Repair", phone: "(808) 942-0404", rating: 4.1 },
  { name: "McKinley Car Wash", address: "1139 Kapiolani Blvd, Honolulu, HI", category: "GAS STATION / CAR WASH", type: "Car Wash", phone: "(808) 596-2609", rating: 4.3 },
  { name: "Don's Makiki Services", address: "1406 S Beretania St, Honolulu, HI", category: "GAS STATION / CAR WASH", type: "Car Wash", phone: "(808) 949-3787", rating: 3.5 },
  { name: "Onoya Ramen", address: "1785 S King St #4, Honolulu, HI", category: "RESTAURANTS (ADDITIONAL)", type: "Ramen", phone: "(808) 888-0607", rating: 4.3 },
  { name: "Ohana Poke House", address: "1960 Kapiolani Blvd #212D, Honolulu, HI", category: "RESTAURANTS (ADDITIONAL)", type: "Poke", phone: "(808) 773-7291", rating: 4.8 },
  { name: "Nabeya Maido", address: "2239 S King St, Honolulu, HI", category: "RESTAURANTS (ADDITIONAL)", type: "Hot Pot", phone: "(808) 739-7739", rating: 4.5 },
  { name: "Wagaya", address: "2080 S King St, Honolulu, HI", category: "RESTAURANTS (ADDITIONAL)", type: "Ramen", phone: "(808) 949-0670", rating: 4.6 },
  { name: "Hong Yeon", address: "909 Isenberg St, Honolulu, HI", category: "RESTAURANTS (ADDITIONAL)", type: "Korean/Chinese", phone: "(808) 367-1909", rating: 4.2 },
  { name: "Golden Eagle Chinese", address: "2334 S King St, Honolulu, HI", category: "RESTAURANTS (ADDITIONAL)", type: "Chinese", phone: "(808) 955-5080", rating: 4.3 },
  { name: "Mama Woo's BBQ", address: "2080 S King St, Honolulu, HI", category: "RESTAURANTS (ADDITIONAL)", type: "Korean BBQ", phone: "(808) 941-6262", rating: 4.6 },
  { name: "UDON YONPACHI", address: "1111 McCully St #B-3, Honolulu, HI", category: "RESTAURANTS (ADDITIONAL)", type: "Udon", phone: "(808) 949-5959", rating: 4.9 },
  { name: "Junpuu", address: "1010 S King St #108, Honolulu, HI", category: "RESTAURANTS (ADDITIONAL)", type: "Ramen", phone: "(808) 260-1901", rating: 4.6 },
  { name: "Manichi Ramen", address: "1430 Kona St #101, Honolulu, HI", category: "RESTAURANTS (ADDITIONAL)", type: "Ramen", phone: "(808) 943-1430", rating: 4.5 },
  { name: "Tanto Gyoza and Ramen Bar", address: "1232 Waimanu St, Honolulu, HI", category: "RESTAURANTS (ADDITIONAL)", type: "Ramen/Gyoza", phone: "(808) 888-0292", rating: 4.5 },
  { name: "Komedokoro M's", address: "438 Hobron Ln #107, Honolulu, HI", category: "RESTAURANTS (ADDITIONAL)", type: "Japanese Deli", phone: "(808) 913-2021", rating: 4.8 },
  { name: "Hotel La Croix", address: "2070 Kalakaua Ave, Honolulu, HI", category: "HOTEL / HOSTEL / LODGING", type: "Hotel", phone: "(808) 942-6060", rating: 4 },
  { name: "Waikiki Grand Hotel", address: "134 Kapahulu Ave, Honolulu, HI", category: "HOTEL / HOSTEL / LODGING", type: "Hotel", phone: "(808) 923-1511", rating: 3.9 },
  { name: "Waikiki Monarch Hotel", address: "444 Niu St, Honolulu, HI", category: "HOTEL / HOSTEL / LODGING", type: "Hotel", phone: "(808) 945-3444", rating: 3.4 },
  { name: "Honu Waikiki by ALOH", address: "1923 Dudoit Ln, Honolulu, HI", category: "HOTEL / HOSTEL / LODGING", type: "Hostel", phone: "(808) 979-4664", rating: 4.9 },
  { name: "Waikiki Beachside Hostel", address: "2556 Lemon Rd, Honolulu, HI", category: "HOTEL / HOSTEL / LODGING", type: "Hostel", phone: "(808) 923-9566", rating: 4.4 },
  { name: "Aqua Aloha Surf Hotel", address: "444 Kanekapolei St, Honolulu, HI", category: "HOTEL / HOSTEL / LODGING", type: "Hotel", phone: "(808) 923-0222", rating: 3.4 },
  { name: "7-Eleven (Kapiolani)", address: "1960 Kapiolani Blvd, Honolulu, HI", category: "CONVENIENCE STORE / SUPERMARKET", type: "Convenience", phone: "(808) 946-7311", rating: 3.7 },
  { name: "7-Eleven (University/King)", address: "2646 S King St, Honolulu, HI", category: "CONVENIENCE STORE / SUPERMARKET", type: "Convenience", phone: "(808) 947-2747", rating: 2.6 },
  { name: "Don Quijote Honolulu", address: "801 Kaheka St #A7, Honolulu, HI", category: "CONVENIENCE STORE / SUPERMARKET", type: "Supermarket", phone: "(808) 973-4800", rating: 4.3 },
  { name: "Times Supermarket McCully", address: "1772 S King St, Honolulu, HI", category: "CONVENIENCE STORE / SUPERMARKET", type: "Supermarket", phone: "(808) 973-5868", rating: 4.2 },
  { name: "HYPE Hot Yoga Waikiki", address: "449 Kapahulu Ave #208, Honolulu, HI", category: "YOGA / PILATES / DANCE", type: "Hot Yoga", phone: "(808) 468-9642", rating: 4.9 },
  { name: "Still & Moving Center", address: "1024 Queen St, Honolulu, HI", category: "YOGA / PILATES / DANCE", type: "Yoga/Wellness", phone: "(808) 397-7678", rating: 5 },
  { name: "Wainani Wellness Center", address: "1144 10th Ave #302, Honolulu, HI", category: "YOGA / PILATES / DANCE", type: "Pilates/Yoga", phone: "(808) 369-1992", rating: 5 },
  { name: "S Pilates Studio", address: "1311 Kapiolani Blvd #501, Honolulu, HI", category: "YOGA / PILATES / DANCE", type: "Pilates", phone: "(808) 500-3288", rating: null },
  { name: "Yoga Room Hawaii", address: "1120 12th Ave, Honolulu, HI", category: "YOGA / PILATES / DANCE", type: "Yoga Studio", phone: "(808) 376-0087", rating: 4.9 },
  { name: "Yoga Waikiki Studio", address: "2424 Kalakaua Ave #216A, Honolulu, HI", category: "YOGA / PILATES / DANCE", type: "Yoga Studio", phone: "(808) 922-0181", rating: 4.5 },
  { name: "Beyond Pilates Studio", address: "627 South St #101, Honolulu, HI", category: "YOGA / PILATES / DANCE", type: "Pilates", phone: "(808) 479-1058", rating: 5 },
  { name: "Pilates O Ka La", address: "3106 Monsarrat Ave, Honolulu, HI", category: "YOGA / PILATES / DANCE", type: "Pilates", phone: "(808) 772-3172", rating: 4.9 },
  { name: "Perfect Portraits Hawaii", address: "1110 University Ave #503, Honolulu, HI", category: "PHOTOGRAPHY STUDIO", type: "Photography", phone: "(808) 222-3467", rating: 4.7 },
  { name: "Photo Art Star", address: "1825 Lime St, Honolulu, HI", category: "PHOTOGRAPHY STUDIO", type: "Photography", phone: "(808) 897-9074", rating: 5 },
  { name: "Ace Portrait Studio", address: "1436 Young St #203, Honolulu, HI", category: "PHOTOGRAPHY STUDIO", type: "Photography", phone: "(808) 591-9220", rating: 4.3 },
  { name: "Studio The Vibe", address: "1200 Ala Moana Blvd, Honolulu, HI", category: "PHOTOGRAPHY STUDIO", type: "Photography", phone: "(808) 222-2523", rating: 5 },
  { name: "Lubera Portraits", address: "1436 Young St, Honolulu, HI", category: "PHOTOGRAPHY STUDIO", type: "Photography", phone: "(808) 489-9768", rating: 5 },
  { name: "Marella Photography", address: "1212 Punahou St, Honolulu, HI", category: "PHOTOGRAPHY STUDIO", type: "Photography", phone: "(808) 722-6672", rating: 5 },
  { name: "House of Photo", address: "1107 S King St, Honolulu, HI", category: "PHOTOGRAPHY STUDIO", type: "Photography", phone: "(808) 596-0440", rating: 3.2 },
  { name: "Kenneth's Photography", address: "2142 S Beretania St, Honolulu, HI", category: "PHOTOGRAPHY STUDIO", type: "Photography", phone: "(808) 941-9591", rating: 2.8 },
  { name: "RP Tax Service", address: "930 McCully St #203, Honolulu, HI", category: "ACCOUNTING / TAX / CPA", type: "Tax Service", phone: "(808) 946-7297", rating: 4.7 },
  { name: "Accounting Management LLC", address: "1648 S King St, Honolulu, HI", category: "ACCOUNTING / TAX / CPA", type: "Accounting", phone: "(808) 537-1212", rating: 5 },
  { name: "G Ushijima CPA LLC", address: "1110 University Ave #508, Honolulu, HI", category: "ACCOUNTING / TAX / CPA", type: "CPA", phone: "(808) 949-5588", rating: 5 },
  { name: "B&Y CPA LLC", address: "1314 S King St #1164, Honolulu, HI", category: "ACCOUNTING / TAX / CPA", type: "CPA", phone: "(808) 781-5024", rating: 4.8 },
  { name: "Manoa Tax Services", address: "438 Hobron Ln, Honolulu, HI", category: "ACCOUNTING / TAX / CPA", type: "Tax Service", phone: "(808) 234-4824", rating: 4.8 },
  { name: "W T Matsuno CPA", address: "1953 S Beretania St #4D, Honolulu, HI", category: "ACCOUNTING / TAX / CPA", type: "CPA", phone: "(808) 951-8899", rating: 5 },
  { name: "H&R Block (Puck's Alley)", address: "2600 S King St #105, Honolulu, HI", category: "ACCOUNTING / TAX / CPA", type: "Tax Service", phone: "(808) 946-4815", rating: 4.8 },
  { name: "Block Advisors", address: "1585 Kapiolani Blvd #722, Honolulu, HI", category: "ACCOUNTING / TAX / CPA", type: "Tax/Accounting", phone: "(808) 955-0120", rating: 4.7 },
  { name: "Slice of Waikiki", address: "333 Seaside Ave, Honolulu, HI", category: "PIZZA / BURGERS / FAST FOOD", type: "Pizza", phone: "(808) 888-0288", rating: 4 },
  { name: "Little Caesars Pizza", address: "2424 S Beretania St, Honolulu, HI", category: "PIZZA / BURGERS / FAST FOOD", type: "Pizza", phone: "(808) 913-2285", rating: 3.8 },
  { name: "Amina Pizzeria", address: "1694 Kalakaua Ave #105, Honolulu, HI", category: "PIZZA / BURGERS / FAST FOOD", type: "Pizza", phone: "(808) 949-3548", rating: 4.5 },
  { name: "Betty's Burgers", address: "1025 University Ave, Honolulu, HI", category: "PIZZA / BURGERS / FAST FOOD", type: "Burgers", phone: "(808) 762-0099", rating: 4.5 },
  { name: "'ili'ili Cash & Carry", address: "2065 S Beretania St, Honolulu, HI", category: "PIZZA / BURGERS / FAST FOOD", type: "Pizza/Deli", phone: "(808) 367-0606", rating: 4.6 },
  { name: "Little G Cafe", address: "808 Sheridan St, Honolulu, HI", category: "PIZZA / BURGERS / FAST FOOD", type: "Pizza", phone: "(808) 699-9116", rating: 4.6 },
  { name: "Teddy's Bigger Burgers", address: "2424 S Beretania St, Honolulu, HI", category: "PIZZA / BURGERS / FAST FOOD", type: "Burgers", phone: "(808) 949-0050", rating: 4.3 },
  { name: "Honolulu Burger Co.", address: "1295 S Beretania St, Honolulu, HI", category: "PIZZA / BURGERS / FAST FOOD", type: "Burgers", phone: "(808) 626-5202", rating: 4.5 },
  { name: "Pieology Pizzeria", address: "2615 S King St #101, Honolulu, HI", category: "PIZZA / BURGERS / FAST FOOD", type: "Pizza", phone: "(808) 952-9232", rating: 4.2 },
  { name: "Chicken University", address: "1910 Ala Moana Blvd #3, Honolulu, HI", category: "PIZZA / BURGERS / FAST FOOD", type: "Chicken/Wings", phone: "(808) 353-8402", rating: 4 },
  { name: "Tadka Indian Cuisine", address: "1960 Kapiolani Blvd #109, Honolulu, HI", category: "INDIAN / VIETNAMESE / INTERNATIONAL", type: "Indian", phone: "(808) 941-0414", rating: 4.3 },
  { name: "Rock 'N Rolls Vietnamese", address: "1778 Ala Moana Blvd #209, Honolulu, HI", category: "INDIAN / VIETNAMESE / INTERNATIONAL", type: "Vietnamese", phone: "(808) 888-0733", rating: 4.5 },
  { name: "New Kamana Kitchen", address: "760 Palani Ave, Honolulu, HI", category: "INDIAN / VIETNAMESE / INTERNATIONAL", type: "Indian", phone: "(808) 734-3160", rating: 4.6 },
  { name: "Pho K&A Vietnamese", address: "760 Kapahulu Ave, Honolulu, HI", category: "INDIAN / VIETNAMESE / INTERNATIONAL", type: "Vietnamese", phone: "(808) 737-8888", rating: 4.7 },
  { name: "Pho Viet Ala Moana", address: "1341 Kapiolani Blvd, Honolulu, HI", category: "INDIAN / VIETNAMESE / INTERNATIONAL", type: "Vietnamese", phone: "(808) 744-0101", rating: 4.5 },
  { name: "Le's Banh Mi", address: "808 Sheridan St #306, Honolulu, HI", category: "INDIAN / VIETNAMESE / INTERNATIONAL", type: "Vietnamese", phone: "(808) 227-3066", rating: 4.8 },
  { name: "Pho 777", address: "1960 Kapiolani Blvd #204, Honolulu, HI", category: "INDIAN / VIETNAMESE / INTERNATIONAL", type: "Vietnamese", phone: "(808) 955-7770", rating: 4 },
  { name: "Cafe Maharani", address: "2509 S King St, Honolulu, HI", category: "INDIAN / VIETNAMESE / INTERNATIONAL", type: "Indian", phone: "(808) 951-7447", rating: 3.9 },
  { name: "Hot Pot Heaven", address: "1960 Kapiolani Blvd #116, Honolulu, HI", category: "INDIAN / VIETNAMESE / INTERNATIONAL", type: "Hot Pot", phone: "(808) 941-1115", rating: 4.7 },
  { name: "Gyotaku Japanese", address: "1824 S King St, Honolulu, HI", category: "ADDITIONAL RESTAURANTS", type: "Japanese", phone: "(808) 949-4584", rating: 4.4 },
  { name: "ROKC Hawaii", address: "280 Beach Walk #106, Honolulu, HI", category: "ADDITIONAL RESTAURANTS", type: "Ramen/Cocktails", phone: "", rating: 5 },
  { name: "Autosource", address: "1488 Kapiolani Blvd, Honolulu, HI", category: "CAR DEALER / AUTO SALES", type: "Car Dealer", phone: "(808) 597-8522", rating: 4.1 },
  { name: "AUTOZILLA (Kalakaua)", address: "1660 Kalakaua Ave #105a, Honolulu, HI", category: "CAR DEALER / AUTO SALES", type: "Car Dealer", phone: "(808) 517-4568", rating: 4.9 },
  { name: "AUTOZILLA (Beretania)", address: "1450 S Beretania St, Honolulu, HI", category: "CAR DEALER / AUTO SALES", type: "Car Dealer", phone: "(808) 517-4568", rating: 5 },
  { name: "Auto Connection LLC", address: "1133 Hopaka St, Honolulu, HI", category: "CAR DEALER / AUTO SALES", type: "Car Dealer", phone: "(808) 596-0733", rating: 4.5 },
  { name: "Auto X-Change Inc", address: "1621 Kalakaua Ave, Honolulu, HI", category: "CAR DEALER / AUTO SALES", type: "Car Dealer", phone: "(808) 593-0599", rating: 4 },
  { name: "Velocity Honolulu", address: "888 Kapiolani Blvd, Honolulu, HI", category: "CAR DEALER / AUTO SALES", type: "Car Dealer", phone: "(808) 593-8888", rating: 4.7 },
  { name: "Grappling Unlimited", address: "1212 Punahou St, Honolulu, HI", category: "MARTIAL ARTS / BOXING / MMA", type: "Martial Arts", phone: "(808) 988-6200", rating: 5 },
  { name: "Relson Gracie Jiu-Jitsu", address: "1712 S King St 2nd Fl, Honolulu, HI", category: "MARTIAL ARTS / BOXING / MMA", type: "Jiu-Jitsu", phone: "(808) 277-1128", rating: 5 },
  { name: "PUNCH FIT HAWAII", address: "1600 Kapiolani Blvd #122, Honolulu, HI", category: "MARTIAL ARTS / BOXING / MMA", type: "Boxing Fitness", phone: "(808) 721-8957", rating: 5 },
  { name: "Red Lotus Hawaii", address: "2357 S Beretania St #B, Honolulu, HI", category: "MARTIAL ARTS / BOXING / MMA", type: "Martial Arts", phone: "", rating: 5 },
  { name: "Mango Tree Fitness", address: "1215 Center St, Honolulu, HI", category: "MARTIAL ARTS / BOXING / MMA", type: "Muay Thai", phone: "(808) 208-7433", rating: 5 },
  { name: "Muay Boran Hawaii", address: "505 Coral St, Honolulu, HI", category: "MARTIAL ARTS / BOXING / MMA", type: "Muay Thai", phone: "(808) 224-8874", rating: 5 },
  { name: "Easy Music Center", address: "1314 S King St #G1, Honolulu, HI", category: "MUSIC STORE / LESSONS", type: "Music Store", phone: "(808) 591-0999", rating: 4.4 },
  { name: "Dan's Guitars", address: "2000 S Beretania St #B, Honolulu, HI", category: "MUSIC STORE / LESSONS", type: "Guitar Shop", phone: "(808) 942-2900", rating: 4.7 },
  { name: "Ukulele Puapua", address: "2255 Kalakaua Ave #13, Honolulu, HI", category: "MUSIC STORE / LESSONS", type: "Ukulele Shop", phone: "(808) 371-9514", rating: 4.6 },
  { name: "Ukulele House", address: "2424 Kalakaua Ave #119, Honolulu, HI", category: "MUSIC STORE / LESSONS", type: "Ukulele Shop", phone: "(808) 922-2889", rating: 4.5 },
  { name: "Ukulele Lab", address: "307 Lewers St #702, Honolulu, HI", category: "MUSIC STORE / LESSONS", type: "Ukulele Shop", phone: "(808) 922-4989", rating: 4.7 },
  { name: "CK Violins", address: "1888 Kalakaua Ave, Honolulu, HI", category: "MUSIC STORE / LESSONS", type: "Violin Shop", phone: "(808) 589-1188", rating: 4.9 },
  { name: "Honolulu Music Lessons", address: "1110 University Ave #505, Honolulu, HI", category: "MUSIC STORE / LESSONS", type: "Music Lessons", phone: "(808) 354-3979", rating: 4.8 },
  { name: "Aloha Music School", address: "725 Kapiolani Blvd #C108, Honolulu, HI", category: "MUSIC STORE / LESSONS", type: "Music School", phone: "(808) 728-6713", rating: 4.4 },
  { name: "Masaki School of Music", address: "1347 Kapiolani Blvd #201, Honolulu, HI", category: "MUSIC STORE / LESSONS", type: "Music School", phone: "(808) 593-9395", rating: 4.4 },
  { name: "Harbors Vintage", address: "1269 S Beretania St, Honolulu, HI", category: "THRIFT / VINTAGE / CONSIGNMENT", type: "Vintage", phone: "(808) 466-9486", rating: 4.9 },
  { name: "homeroom", address: "1269 S Beretania St 2nd Fl, Honolulu, HI", category: "THRIFT / VINTAGE / CONSIGNMENT", type: "Thrift/Vintage", phone: "(808) 378-7667", rating: 4.8 },
  { name: "Sonador Vintage", address: "1269 S Beretania St, Honolulu, HI", category: "THRIFT / VINTAGE / CONSIGNMENT", type: "Vintage", phone: "(510) 447-0781", rating: 5 },
  { name: "Velzy Vintage", address: "1269 S Beretania St, Honolulu, HI", category: "THRIFT / VINTAGE / CONSIGNMENT", type: "Vintage", phone: "(407) 790-1142", rating: 4.9 },
  { name: "DeStash Hawaii", address: "736 South St #103, Honolulu, HI", category: "THRIFT / VINTAGE / CONSIGNMENT", type: "Vintage", phone: "(808) 200-7874", rating: 5 },
  { name: "ECO TOWN SELECT", address: "1450 Ala Moana Blvd #1243, Honolulu, HI", category: "THRIFT / VINTAGE / CONSIGNMENT", type: "Thrift", phone: "(808) 942-4433", rating: 3.4 },
  { name: "Savers", address: "2220 S King St, Honolulu, HI", category: "THRIFT / VINTAGE / CONSIGNMENT", type: "Thrift Store", phone: "(808) 842-0061", rating: 4.1 },
  { name: "Salvage Public", address: "1170 Auahi St, Honolulu, HI", category: "THRIFT / VINTAGE / CONSIGNMENT", type: "Clothing/Vintage", phone: "(808) 380-7888", rating: 4.8 },
  { name: "Kamaaina Locksmith", address: "1650 Ala Moana Blvd #3505, Honolulu, HI", category: "LOCKSMITH / KEY SERVICE", type: "Locksmith", phone: "(808) 202-3257", rating: 4.9 },
  { name: "Honolulu Locksmith", address: "500 Ala Moana Blvd #7-400, Honolulu, HI", category: "LOCKSMITH / KEY SERVICE", type: "Locksmith", phone: "(808) 378-7552", rating: 4.9 },
  { name: "Affordable Locksmith Hawaii", address: "1259 S Beretania St #3, Honolulu, HI", category: "LOCKSMITH / KEY SERVICE", type: "Locksmith", phone: "(808) 201-9745", rating: 4.2 },
  { name: "The Key Fob And Remote Shop", address: "930 McCully St #200, Honolulu, HI", category: "LOCKSMITH / KEY SERVICE", type: "Key/Fob Service", phone: "(808) 435-5804", rating: 4.6 },
  { name: "KeyMe Locksmiths", address: "888 Kapahulu Ave, Honolulu, HI", category: "LOCKSMITH / KEY SERVICE", type: "Locksmith Kiosk", phone: "(808) 517-5753", rating: 4.1 },
  { name: "Waialae Plumbing", address: "825 Halekauwila St #D, Honolulu, HI", category: "PLUMBER / CONTRACTOR", type: "Plumber", phone: "(808) 735-8595", rating: 4.9 },
  { name: "Best Plumber Honolulu", address: "1901 Kapiolani Blvd, Honolulu, HI", category: "PLUMBER / CONTRACTOR", type: "Plumber", phone: "(808) 215-3507", rating: 5 },
  { name: "Pineapple Plumbing", address: "1207 Hopaka St, Honolulu, HI", category: "PLUMBER / CONTRACTOR", type: "Plumber", phone: "(808) 202-2939", rating: 4.5 },
  { name: "Western Pacific Mechanical", address: "2722 S King St, Honolulu, HI", category: "PLUMBER / CONTRACTOR", type: "HVAC/Mechanical", phone: "(808) 537-9712", rating: 4.5 },
  { name: "You Move Me Honolulu", address: "821 Cedar St #B, Honolulu, HI", category: "MOVING COMPANY / STORAGE", type: "Moving Company", phone: "(808) 379-3850", rating: 4.9 },
  { name: "Malama Moving Company", address: "661 Keeaumoku St #105, Honolulu, HI", category: "MOVING COMPANY / STORAGE", type: "Moving Company", phone: "(808) 699-4070", rating: 4.7 },
  { name: "Ewa Moving Co.", address: "1415 Kinau St #A1, Honolulu, HI", category: "MOVING COMPANY / STORAGE", type: "Moving Company", phone: "(808) 300-0223", rating: 4.9 },
  { name: "Help-U-Move Hawaii", address: "1288 Kapiolani Blvd #3202, Honolulu, HI", category: "MOVING COMPANY / STORAGE", type: "Moving Company", phone: "(808) 780-2165", rating: 5 },
  { name: "Storkeeper Self Storage", address: "1687 Kalauokalani Way #A, Honolulu, HI", category: "MOVING COMPANY / STORAGE", type: "Storage", phone: "(808) 941-1180", rating: 4.7 },
  { name: "U-Haul Kakaako", address: "438 Kamakee St, Honolulu, HI", category: "MOVING COMPANY / STORAGE", type: "Moving/Storage", phone: "(808) 725-3405", rating: 4.5 },
  { name: "Angels At Play Preschool", address: "2062 S King St, Honolulu, HI", category: "DAYCARE / PRESCHOOL", type: "Preschool", phone: "(808) 944-2625", rating: 5 },
  { name: "Central Union Church Preschool", address: "1660 S Beretania St, Honolulu, HI", category: "DAYCARE / PRESCHOOL", type: "Preschool", phone: "(808) 946-4025", rating: 5 },
  { name: "KCAA Mother Rice Preschool", address: "2707 S King St, Honolulu, HI", category: "DAYCARE / PRESCHOOL", type: "Preschool", phone: "(808) 946-4072", rating: 4 },
  { name: "Happy Keiki Preschool", address: "1035 University Ave, Honolulu, HI", category: "DAYCARE / PRESCHOOL", type: "Preschool", phone: "(808) 381-8185", rating: null },
  { name: "Olivet Baptist Preschool", address: "1775 S Beretania St, Honolulu, HI", category: "DAYCARE / PRESCHOOL", type: "Preschool", phone: "(808) 949-7548", rating: 3.7 },
  { name: "Kamaaina Kids Honolulu", address: "930 Lunalilo St, Honolulu, HI", category: "DAYCARE / PRESCHOOL", type: "Preschool", phone: "(808) 599-2807", rating: 4.4 },
  { name: "Tournet Hawaii", address: "1888 Kalakaua Ave #C109, Honolulu, HI", category: "TRAVEL AGENCY / TOUR OPERATOR", type: "Tour Agency", phone: "(808) 922-1122", rating: 5 },
  { name: "Hawaii Global Holiday", address: "2032 S Beretania St, Honolulu, HI", category: "TRAVEL AGENCY / TOUR OPERATOR", type: "Travel Agency", phone: "(808) 921-0999", rating: 3.9 },
  { name: "HIS Hawaii Ala Moana", address: "1450 Ala Moana Blvd #1206, Honolulu, HI", category: "TRAVEL AGENCY / TOUR OPERATOR", type: "Travel Agency", phone: "(808) 922-2211", rating: 4.3 },
  { name: "Hoku Hawaii Tours", address: "438 Hobron Ln #500, Honolulu, HI", category: "TRAVEL AGENCY / TOUR OPERATOR", type: "Tour Operator", phone: "", rating: 4.8 },
  { name: "1 Epic Tour LLC", address: "2700 S King St #11192, Honolulu, HI", category: "TRAVEL AGENCY / TOUR OPERATOR", type: "Tour Operator", phone: "(808) 354-8021", rating: 4.9 },
  { name: "N & K Travel Service", address: "758 Kapahulu Ave #220, Honolulu, HI", category: "TRAVEL AGENCY / TOUR OPERATOR", type: "Travel Agency", phone: "(808) 739-9010", rating: 5 },
  { name: "Hawaii Russian Tours", address: "1720 Ala Moana Blvd #1402A, Honolulu, HI", category: "TRAVEL AGENCY / TOUR OPERATOR", type: "Tour Agency", phone: "(808) 796-8713", rating: 4.8 },
  { name: "HNL Travel Associates", address: "1245 Young St #203, Honolulu, HI", category: "TRAVEL AGENCY / TOUR OPERATOR", type: "Travel Agency", phone: "(808) 591-2011", rating: 4.2 },
  { name: "Yim & Yempuku Law", address: "2054 S Beretania St, Honolulu, HI", category: "LAW OFFICE / ATTORNEY", type: "Estate Planning", phone: "(808) 524-0251", rating: 4.8 },
  { name: "Law Offices Steve Cedillos", address: "1670 Makaloa St #204-338, Honolulu, HI", category: "LAW OFFICE / ATTORNEY", type: "Attorney", phone: "(808) 201-0496", rating: 4.3 },
  { name: "Go Law Office LLLC", address: "1441 Kapiolani Blvd #910, Honolulu, HI", category: "LAW OFFICE / ATTORNEY", type: "Attorney", phone: "(808) 679-2049", rating: 5 },
  { name: "Amphay Champathong Estate", address: "1585 Kapiolani Blvd #1111, Honolulu, HI", category: "LAW OFFICE / ATTORNEY", type: "Estate Planning", phone: "(808) 218-9301", rating: 5 },
  { name: "Stephen S Choi Attorney", address: "1555 Kapiolani Blvd #1111, Honolulu, HI", category: "LAW OFFICE / ATTORNEY", type: "Attorney", phone: "(808) 286-4248", rating: 5 },
  { name: "Cleaning Service Honolulu", address: "1066 Green St, Honolulu, HI", category: "CLEANING SERVICE", type: "Cleaning", phone: "(925) 895-2027", rating: 5 },
  { name: "Maid In Oahu", address: "1314 S King St #723, Honolulu, HI", category: "CLEANING SERVICE", type: "Cleaning", phone: "(808) 664-0036", rating: 4.9 },
  { name: "Diamond Bright Cleaning", address: "3841A Keanu St, Honolulu, HI", category: "CLEANING SERVICE", type: "Cleaning", phone: "(808) 728-0379", rating: 4.9 },
  { name: "Boba House", address: "1610 S King St, Honolulu, HI", category: "BUBBLE TEA / BOBA / JUICE", type: "Boba Tea", phone: "(808) 200-5070", rating: 4.3 },
  { name: "Plus Two Shave Ice & Boba", address: "1694A Kalakaua Ave, Honolulu, HI", category: "BUBBLE TEA / BOBA / JUICE", type: "Boba/Shave Ice", phone: "(808) 590-1590", rating: 3.7 },
  { name: "Little Sweet", address: "756 Palani Ave, Honolulu, HI", category: "BUBBLE TEA / BOBA / JUICE", type: "Boba/Dessert", phone: "(808) 732-1000", rating: 4.9 },
  { name: "Lunar Tea", address: "2334 S King St #102, Honolulu, HI", category: "BUBBLE TEA / BOBA / JUICE", type: "Boba Tea", phone: "(808) 892-1018", rating: 4.8 },
  { name: "QQ Tea & Vegetarian House", address: "931 University Ave #109, Honolulu, HI", category: "BUBBLE TEA / BOBA / JUICE", type: "Boba/Vegetarian", phone: "(808) 941-6688", rating: 4.7 },
  { name: "GangnamCha", address: "1450 Ala Moana Blvd, Honolulu, HI", category: "BUBBLE TEA / BOBA / JUICE", type: "Boba Tea", phone: "(808) 336-1198", rating: 4.8 },
  { name: "Aloha Bowls and Tea", address: "2005 Kalia Rd, Honolulu, HI", category: "BUBBLE TEA / BOBA / JUICE", type: "Acai/Boba", phone: "(808) 807-7733", rating: 4.5 },
  { name: "We Fix Phones Oahu", address: "2304 S King St #101, Honolulu, HI", category: "CELL PHONE REPAIR / ELECTRONICS", type: "Phone Repair", phone: "(808) 388-3854", rating: 4.9 },
  { name: "Aloha Phone Repair by TCA", address: "801 Kaheka St #A7, Honolulu, HI", category: "CELL PHONE REPAIR / ELECTRONICS", type: "Phone Repair", phone: "(808) 944-8886", rating: 4.9 },
  { name: "Waikiki Cell Phone Repair", address: "465 Kapahulu Ave #101, Honolulu, HI", category: "CELL PHONE REPAIR / ELECTRONICS", type: "Phone Repair", phone: "(808) 600-1665", rating: 4.9 },
  { name: "Tricked Out Phone Repair", address: "1450 Ala Moana Blvd #1044, Honolulu, HI", category: "CELL PHONE REPAIR / ELECTRONICS", type: "Phone Repair", phone: "(808) 944-3404", rating: 4.8 },
  { name: "WIRELESS CITY", address: "1670 Makaloa St #104, Honolulu, HI", category: "CELL PHONE REPAIR / ELECTRONICS", type: "Cell Phone Store", phone: "(808) 447-7722", rating: 5 },
  { name: "Hoku Wireless", address: "159 Kaiulani Ave #102, Honolulu, HI", category: "CELL PHONE REPAIR / ELECTRONICS", type: "Cell Phone Store", phone: "", rating: 5 },
  { name: "SuperGeeks", address: "2304 S King St #101, Honolulu, HI", category: "CELL PHONE REPAIR / ELECTRONICS", type: "Computer Repair", phone: "(808) 531-4335", rating: 4.8 },
  { name: "Personal Touch Computers", address: "2333 Kapiolani Blvd #1712, Honolulu, HI", category: "CELL PHONE REPAIR / ELECTRONICS", type: "Computer Repair", phone: "(808) 561-7029", rating: 4.9 },
  { name: "Dive Oahu & Surf Kuhio", address: "2425 Kalakaua Ave, Honolulu, HI", category: "SURF SHOP / DIVE / WATER SPORTS", type: "Surf/Dive Shop", phone: "(808) 922-3483", rating: 3.7 },
  { name: "Blue Planet Surf Shop", address: "1221 Kona St, Honolulu, HI", category: "SURF SHOP / DIVE / WATER SPORTS", type: "Surf/SUP Shop", phone: "(808) 596-7755", rating: 4.8 },
  { name: "Honolulu Scuba Company", address: "670 Auahi St #A-1, Honolulu, HI", category: "SURF SHOP / DIVE / WATER SPORTS", type: "Dive Shop", phone: "(808) 201-4711", rating: 4.5 },
  { name: "Aloha Scuba Diving", address: "410 Atkinson Dr #1F3, Honolulu, HI", category: "SURF SHOP / DIVE / WATER SPORTS", type: "Dive Shop", phone: "(808) 622-3483", rating: 4.8 },
  { name: "Dive Oahu Kewalo Basin", address: "1085 Ala Moana Blvd #109, Honolulu, HI", category: "SURF SHOP / DIVE / WATER SPORTS", type: "Dive Shop", phone: "(808) 922-3483", rating: 4.6 },
  { name: "Westside Dive Honolulu", address: "670 Auahi St, Honolulu, HI", category: "SURF SHOP / DIVE / WATER SPORTS", type: "Dive Shop", phone: "(808) 312-1426", rating: 5 },
  { name: "Toma Karaoke", address: "2221 S Beretania St, Honolulu, HI", category: "KARAOKE / BAR / NIGHTLIFE", type: "Karaoke", phone: "(808) 947-7022", rating: 4.4 },
  { name: "Kingyo Karaoke Lounge", address: "1939 S King St, Honolulu, HI", category: "KARAOKE / BAR / NIGHTLIFE", type: "Karaoke/Bar", phone: "(808) 744-7970", rating: 4.3 },
  { name: "WAVE808 Karaoke", address: "808 Sheridan St #201, Honolulu, HI", category: "KARAOKE / BAR / NIGHTLIFE", type: "Karaoke", phone: "(808) 509-8080", rating: 4.8 },
  { name: "Hawaii Voice Karaoke", address: "1491 S King St, Honolulu, HI", category: "KARAOKE / BAR / NIGHTLIFE", type: "Karaoke/Bar", phone: "(808) 900-7999", rating: 4.5 },
  { name: "In Between", address: "2155 Lauula St, Honolulu, HI", category: "KARAOKE / BAR / NIGHTLIFE", type: "Karaoke Bar", phone: "(808) 926-7060", rating: 4.5 },
  { name: "Wang Chung's Karaoke", address: "2424 Koa Ave, Honolulu, HI", category: "KARAOKE / BAR / NIGHTLIFE", type: "Karaoke Bar", phone: "(808) 201-6369", rating: 4.2 },
  { name: "AnyPlace Cocktail Lounge", address: "1018 McCully St, Honolulu, HI", category: "KARAOKE / BAR / NIGHTLIFE", type: "Sports Bar", phone: "(808) 947-8977", rating: 4.5 },
  { name: "Chiko's Tavern", address: "930 McCully St, Honolulu, HI", category: "KARAOKE / BAR / NIGHTLIFE", type: "Bar/Karaoke", phone: "(808) 949-5440", rating: 4.5 },
  { name: "Di's Karaoke", address: "1338 Young St, Honolulu, HI", category: "KARAOKE / BAR / NIGHTLIFE", type: "Karaoke/Bar", phone: "(808) 591-6590", rating: 4 },
  { name: "HomeWorld Honolulu", address: "702 S Beretania St, Honolulu, HI", category: "FURNITURE / HOME DECOR / MATTRESS", type: "Furniture", phone: "(808) 543-5300", rating: 4.8 },
  { name: "SlumberWorld Honolulu", address: "702 S Beretania St, Honolulu, HI", category: "FURNITURE / HOME DECOR / MATTRESS", type: "Mattress", phone: "(808) 545-3555", rating: 4.9 },
  { name: "Creative Furniture", address: "943 Waimanu St, Honolulu, HI", category: "FURNITURE / HOME DECOR / MATTRESS", type: "Futon/Furniture", phone: "(808) 591-2833", rating: 4.3 },
  { name: "Marlowe Furnishings", address: "307C Kamani St, Honolulu, HI", category: "FURNITURE / HOME DECOR / MATTRESS", type: "Furniture", phone: "(808) 451-7771", rating: 5 },
  { name: "apt. by HomeWorld", address: "455 Ward Ave, Honolulu, HI", category: "FURNITURE / HOME DECOR / MATTRESS", type: "Furniture", phone: "(808) 791-3300", rating: 4.7 },
  { name: "Red Knot Honolulu", address: "702 S Beretania St, Honolulu, HI", category: "FURNITURE / HOME DECOR / MATTRESS", type: "Furniture", phone: "(808) 543-5360", rating: 4.7 },
  { name: "Honolulu Design Center", address: "1250 Kapiolani Blvd, Honolulu, HI", category: "FURNITURE / HOME DECOR / MATTRESS", type: "Furniture/Decor", phone: "(808) 956-1250", rating: 4.2 },
  { name: "All Dogs Grooming", address: "1411 Kalakaua Ave, Honolulu, HI", category: "PET GROOMING / VET (ADDITIONAL)", type: "Pet Grooming", phone: "(808) 799-0988", rating: 4.9 },
  { name: "Hawaii Pet Groomer", address: "2909 Lowrey Ave #E, Honolulu, HI", category: "PET GROOMING / VET (ADDITIONAL)", type: "Pet Grooming", phone: "(808) 425-2869", rating: 5 },
  { name: "Pets in the City", address: "1350 S King St #117, Honolulu, HI", category: "PET GROOMING / VET (ADDITIONAL)", type: "Pet Daycare", phone: "(808) 593-1505", rating: 4.6 },
  { name: "Ali'i Animal Hospital", address: "942 Kawaiahao St, Honolulu, HI", category: "PET GROOMING / VET (ADDITIONAL)", type: "Vet/Pet Resort", phone: "(808) 234-3441", rating: 4.4 },
  { name: "The Itchy Pooch Salon", address: "1481 S King St #107, Honolulu, HI", category: "PET GROOMING / VET (ADDITIONAL)", type: "Pet Grooming", phone: "(808) 445-2631", rating: 4.8 },
  { name: "Kalihi Pet Clinic", address: "2203 S Beretania St #C, Honolulu, HI", category: "PET GROOMING / VET (ADDITIONAL)", type: "Vet", phone: "(808) 951-8808", rating: 4.7 },
  { name: "FedEx Office (Kapiolani)", address: "1500 Kapiolani Blvd, Honolulu, HI", category: "PRINTING / SHIPPING / NOTARY", type: "Print/Ship", phone: "(808) 944-8500", rating: 2.9 },
  { name: "The UPS Store (Kapahulu)", address: "758 Kapahulu Ave #100, Honolulu, HI", category: "PRINTING / SHIPPING / NOTARY", type: "Shipping/Notary", phone: "(808) 734-2928", rating: 4 },
  { name: "The UPS Store (Manoa)", address: "2855 E Manoa Rd #105, Honolulu, HI", category: "PRINTING / SHIPPING / NOTARY", type: "Shipping/Notary", phone: "(808) 888-2392", rating: 4 },
  { name: "City Mill Kaimuki", address: "3086 Waialae Ave, Honolulu, HI", category: "HARDWARE / HOME IMPROVEMENT", type: "Hardware", phone: "(808) 735-7636", rating: 4.2 },
  { name: "Kaimuki Ace Hardware", address: "3384 Waialae Ave, Honolulu, HI", category: "HARDWARE / HOME IMPROVEMENT", type: "Hardware", phone: "(808) 732-2888", rating: 4 },
  { name: "Sherwin-Williams", address: "2733 S King St, Honolulu, HI", category: "HARDWARE / HOME IMPROVEMENT", type: "Paint Store", phone: "(808) 947-8449", rating: 4.8 },
  { name: "Soon Alterations", address: "1641 Kalakaua Ave #23, Honolulu, HI", category: "DRY CLEANER / TAILOR / ALTERATIONS", type: "Alterations", phone: "(808) 941-9609", rating: 4.9 },
  { name: "Linh's Alterations", address: "1232 Keeaumoku St, Honolulu, HI", category: "DRY CLEANER / TAILOR / ALTERATIONS", type: "Alterations", phone: "(808) 955-3730", rating: 4.4 },
  { name: "Aloha Dry Cleaners", address: "1450 Ala Moana Blvd #1225, Honolulu, HI", category: "DRY CLEANER / TAILOR / ALTERATIONS", type: "Dry Cleaner", phone: "(808) 597-1766", rating: 4.2 },
  { name: "Sook Hi's Alteration", address: "818 Sheridan St #204, Honolulu, HI", category: "DRY CLEANER / TAILOR / ALTERATIONS", type: "Alterations", phone: "(808) 949-6858", rating: 4.8 },
  { name: "Sew Good Tailor", address: "1411 S King St #207, Honolulu, HI", category: "DRY CLEANER / TAILOR / ALTERATIONS", type: "Tailor", phone: "(808) 955-4663", rating: 4.2 },
  { name: "Hakuyosha Dry Cleaners", address: "1206 S King St, Honolulu, HI", category: "DRY CLEANER / TAILOR / ALTERATIONS", type: "Dry Cleaner", phone: "(808) 596-2827", rating: 4.1 },
  { name: "Li Sewing", address: "1259 S Beretania St #19, Honolulu, HI", category: "DRY CLEANER / TAILOR / ALTERATIONS", type: "Tailor", phone: "(808) 597-1335", rating: 4.8 },
  { name: "Asia Tailor", address: "1330 S Beretania St #309, Honolulu, HI", category: "DRY CLEANER / TAILOR / ALTERATIONS", type: "Tailor", phone: "(808) 596-2742", rating: 4.8 },
  { name: "Jenny Alterations", address: "434 Ena Rd, Honolulu, HI", category: "DRY CLEANER / TAILOR / ALTERATIONS", type: "Alterations", phone: "(808) 955-8831", rating: 5 },
  { name: "Marie Louise Cleaners", address: "331G Kamani St, Honolulu, HI", category: "DRY CLEANER / TAILOR / ALTERATIONS", type: "Dry Cleaner", phone: "(808) 593-1110", rating: 4.5 },
  { name: "Honolulu Trading Company", address: "1108 Pensacola St, Honolulu, HI", category: "PAWN SHOP / GOLD EXCHANGE", type: "Gold/Jewelry", phone: "(808) 536-9739", rating: 4.5 },
  { name: "Crown Time House", address: "1017 Pensacola St, Honolulu, HI", category: "WATCH REPAIR / JEWELRY", type: "Watch Repair", phone: "(808) 620-2730", rating: 4.3 },
  { name: "JES Jewelry Co.", address: "745 Keeaumoku St #101, Honolulu, HI", category: "WATCH REPAIR / JEWELRY", type: "Jewelry", phone: "(808) 941-1573", rating: 4.9 },
  { name: "The Wedding Ring Shop", address: "1181 Kapiolani Blvd, Honolulu, HI", category: "WATCH REPAIR / JEWELRY", type: "Jewelry", phone: "(808) 945-7766", rating: 4.9 },
  { name: "Thai Tacos @ Waikiki", address: "208A Kapuni St, Honolulu, HI", category: "THAI / MEDITERRANEAN / INTERNATIONAL", type: "Thai Fusion", phone: "(808) 798-4488", rating: 4.8 },
  { name: "Siam Square", address: "408 Lewers St, Honolulu, HI", category: "THAI / MEDITERRANEAN / INTERNATIONAL", type: "Thai", phone: "(808) 923-5320", rating: 4.4 },
  { name: "Noi Thai Cuisine", address: "2301 Kalakaua Ave, Honolulu, HI", category: "THAI / MEDITERRANEAN / INTERNATIONAL", type: "Thai", phone: "(808) 664-4039", rating: 4.3 },
  { name: "SERA Restaurant & Bar", address: "1390 Kapiolani Blvd, Honolulu, HI", category: "THAI / MEDITERRANEAN / INTERNATIONAL", type: "Mediterranean", phone: "(808) 450-3036", rating: 4.1 },
  { name: "Da Spot", address: "2469 S King St, Honolulu, HI", category: "THAI / MEDITERRANEAN / INTERNATIONAL", type: "Mediterranean/Halal", phone: "(808) 941-1313", rating: 4.5 },
  { name: "Leo's Taverna Express", address: "801 Kaheka St #A7, Honolulu, HI", category: "THAI / MEDITERRANEAN / INTERNATIONAL", type: "Greek", phone: "(808) 949-2225", rating: 4.4 },
  { name: "Honolulu Chiropractic", address: "1314 S King St #1655, Honolulu, HI", category: "CHIROPRACTIC / MASSAGE / WELLNESS", type: "Chiropractic", phone: "(808) 924-7246", rating: 4.9 },
  { name: "Ke'ale Chiropractic", address: "1314 S King St #425b, Honolulu, HI", category: "CHIROPRACTIC / MASSAGE / WELLNESS", type: "Chiropractic", phone: "(808) 763-8387", rating: 5 },
  { name: "Honolulu Wellness Group", address: "1314 S King St #1656, Honolulu, HI", category: "CHIROPRACTIC / MASSAGE / WELLNESS", type: "Chiropractic", phone: "(808) 923-8378", rating: 5 },
  { name: "Manoa Chiropractic", address: "2851 E Manoa Rd #1-205, Honolulu, HI", category: "CHIROPRACTIC / MASSAGE / WELLNESS", type: "Chiropractic", phone: "(808) 988-6113", rating: 4.8 },
  { name: "East 2 West Acupuncture", address: "1024 Queen St, Honolulu, HI", category: "CHIROPRACTIC / MASSAGE / WELLNESS", type: "Acupuncture/Massage", phone: "(808) 364-1555", rating: 4.8 },
  { name: "LOKAHI Wellness Method", address: "959 Waimanu St, Honolulu, HI", category: "CHIROPRACTIC / MASSAGE / WELLNESS", type: "Acupuncture/Massage", phone: "(808) 897-9654", rating: 5 },
];
