// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/services-section/Bento.tsx": () => import("../components/mockups/services-section/Bento.tsx"),
  "./components/mockups/services-section/IconGrid.tsx": () => import("../components/mockups/services-section/IconGrid.tsx"),
  "./components/mockups/services-section/TabbedSpotlight.tsx": () => import("../components/mockups/services-section/TabbedSpotlight.tsx")
};
